import type { WizardStyles } from './types'
import { tokens } from '@/lib/design/tokens'

/*
  Merchant onboarding wizard styles — "SaaS Commerce Modern" palette.
  Navy dark sidebar + white main area + indigo CTA pattern.
*/
const c = tokens.color
const r = tokens.radius
const f = tokens.font.sans

export const styles: WizardStyles = {
  wizard: {
    display: 'flex', height: '100vh', maxHeight: '100vh', overflow: 'hidden',
    fontFamily: f, background: c.background, color: c.text,
  },

  sidebar: {
    width: 210, minWidth: 210,
    background: c.navy,
    color: '#f7f9fb',
    display: 'flex', flexDirection: 'column',
    padding: '20px 14px', gap: 0, overflowY: 'auto',
  },
  sidebarBrand: {
    display: 'flex', alignItems: 'center', gap: 8,
    marginBottom: 20, paddingBottom: 14,
    borderBottom: '1px solid rgba(255,255,255,0.1)',
  },
  sidebarLogo: { fontSize: 20, color: c.primary },
  sidebarTitle: { fontSize: 15, fontWeight: 700, letterSpacing: '-0.01em', color: '#fff' },
  stepList: { display: 'flex', flexDirection: 'column', gap: 1, flex: 1 },
  stepItem: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '8px 10px', borderRadius: r.md, cursor: 'default', transition: 'background 0.2s',
  },
  stepItemActive: { background: 'rgba(79,70,229,0.18)' },
  stepItemDone: { opacity: 0.55 },
  stepIconWrap: {
    width: 26, height: 26, borderRadius: r.sm,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 12, background: 'rgba(255,255,255,0.07)',
    color: 'rgba(255,255,255,0.4)', flexShrink: 0,
  },
  stepIconActive: { background: c.primary, color: '#fff' },
  stepIconDone: { background: c.successSoft, color: c.success },
  stepLabel: { fontSize: 12, fontWeight: 500, margin: 0, color: '#f7f9fb', lineHeight: 1.3 },
  stepNum: { fontSize: 9, color: 'rgba(255,255,255,0.3)', margin: 0 },
  progressWrap: { marginTop: 16, paddingTop: 12, borderTop: '1px solid rgba(255,255,255,0.08)' },
  progressBar: { height: 3, background: 'rgba(255,255,255,0.1)', borderRadius: 2, overflow: 'hidden' },
  progressFill: { height: '100%', background: c.primary, borderRadius: 2, transition: 'width 0.4s' },
  progressLabel: { fontSize: 11, color: 'rgba(255,255,255,0.3)', margin: '6px 0 0', textAlign: 'right' },

  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 },
  stepHeader: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: '14px 24px', borderBottom: `1px solid ${c.border}`,
    background: c.surface, flexShrink: 0,
  },
  stepHeaderIcon: { fontSize: 22, lineHeight: 1, color: c.primary },
  stepHeaderTitle: { fontSize: 18, fontWeight: 700, margin: 0, letterSpacing: '-0.01em', color: c.navy },
  stepHeaderSub: { fontSize: 12, color: c.textFaint, margin: '2px 0 0' },
  stepBody: { flex: 1, overflowY: 'auto', padding: '20px 24px', minHeight: 0 },
  navBar: {
    display: 'flex', alignItems: 'center', padding: '12px 24px',
    borderTop: `1px solid ${c.border}`, background: c.surface, gap: 12, flexShrink: 0,
  },
  backBtn: {
    padding: '9px 18px', borderRadius: r.md,
    border: `1px solid ${c.border}`, background: 'transparent',
    cursor: 'pointer', fontSize: 13, color: c.textMuted, fontFamily: f,
  },
  nextBtn: {
    padding: '10px 24px', borderRadius: r.md, border: 'none',
    background: c.primary, color: '#fff', cursor: 'pointer',
    fontSize: 14, fontWeight: 600, letterSpacing: '-0.01em', fontFamily: f,
  },
  nextBtnDisabled: { background: c.border, cursor: 'not-allowed', color: c.textFaint },
  publishBtn: {
    padding: '10px 28px', borderRadius: r.md, border: 'none',
    background: c.success, color: '#fff', cursor: 'pointer',
    fontSize: 14, fontWeight: 700, letterSpacing: '-0.01em', fontFamily: f,
  },

  stepContent: { maxWidth: '100%', width: '100%' },
  fieldGroup: { marginBottom: 24 },
  label: { fontSize: 12, fontWeight: 600, color: c.textMuted, display: 'block', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.04em' },
  input: {
    width: '100%', padding: '10px 12px', fontSize: 14,
    border: `1.5px solid ${c.border}`, borderRadius: r.md,
    background: c.surface, color: c.navy, outline: 'none',
    boxSizing: 'border-box', marginBottom: 8, fontFamily: f,
    transition: 'border-color 0.15s',
  },
  textarea: {
    width: '100%', padding: '10px 12px', fontSize: 13,
    border: `1.5px solid ${c.border}`, borderRadius: r.md,
    background: c.surface, color: c.navy, outline: 'none',
    boxSizing: 'border-box', resize: 'vertical', fontFamily: f, marginBottom: 8,
  },
  hint: { fontSize: 12, color: c.textFaint, margin: '4px 0 0' },
  emptyHint: { fontSize: 12, color: c.textFaint, textAlign: 'center', margin: '16px 0' },

  uploadZone: {
    border: `2px dashed ${c.borderStrong}`, borderRadius: r.lg,
    padding: '32px 24px', textAlign: 'center', cursor: 'pointer',
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6,
    background: c.surfaceLow, transition: 'border-color 0.2s',
  },
  uploadZoneFilled: { borderColor: c.primary, background: c.primarySoft },
  uploadIcon: { fontSize: 24, color: c.primary },
  uploadText: { fontSize: 13, fontWeight: 500, color: c.textMuted },
  uploadSub: { fontSize: 11, color: c.textFaint },
  logoPreview: { maxHeight: 80, maxWidth: '100%', objectFit: 'contain' },
  clearBtn: { fontSize: 12, color: c.textFaint, background: 'none', border: 'none', cursor: 'pointer', padding: '4px 0', textDecoration: 'underline', fontFamily: f },

  catalogLayout: { display: 'flex', gap: 16, height: '100%', minHeight: 360 },
  categoryPanel: {
    width: 200, flexShrink: 0, border: `1px solid ${c.border}`,
    borderRadius: r.lg, background: c.surface, padding: 12,
    display: 'flex', flexDirection: 'column', gap: 8,
    boxShadow: tokens.shadow.card,
  },
  productPanel: {
    flex: 1, border: `1px solid ${c.border}`,
    borderRadius: r.lg, background: c.surface, padding: 16, overflow: 'auto',
    boxShadow: tokens.shadow.card,
  },
  panelTitle: { fontSize: 11, fontWeight: 700, color: c.textMuted, margin: '0 0 8px', textTransform: 'uppercase', letterSpacing: '0.06em' },
  addRow: { display: 'flex', gap: 6, alignItems: 'center' },
  addBtn: {
    width: 32, height: 36, borderRadius: r.sm,
    border: 'none', background: c.primary, color: '#fff',
    cursor: 'pointer', fontSize: 18, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  catList: { flex: 1, overflowY: 'auto' },
  catItem: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '8px 10px', borderRadius: r.sm, cursor: 'pointer', transition: 'background 0.15s',
  },
  catItemActive: { background: c.primarySoft },
  catName: { fontSize: 13, color: c.navy, fontWeight: 500 },
  catCount: { fontSize: 11, background: c.surfaceLow, color: c.textMuted, borderRadius: 4, padding: '1px 5px' },
  removeBtn: { background: 'none', border: 'none', cursor: 'pointer', color: c.textFaint, fontSize: 16, lineHeight: 1, padding: 0, flexShrink: 0 },
  emptyPanel: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 8 },
  productGrid: { display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 16 },
  productCard: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '8px 10px',
    border: `1px solid ${c.border}`, borderRadius: r.md, background: c.surfaceLow,
  },
  productThumb: { width: 40, height: 40, objectFit: 'cover', borderRadius: r.sm, flexShrink: 0 },
  productThumbEmpty: {
    width: 40, height: 40, borderRadius: r.sm, background: c.border,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 18, color: c.textFaint, flexShrink: 0,
  },
  productName: { fontSize: 13, fontWeight: 500, margin: 0, color: c.navy },
  productPrice: { fontSize: 12, color: c.textMuted, margin: 0 },
  addProductForm: { borderTop: `1px solid ${c.border}`, paddingTop: 16, display: 'flex', flexDirection: 'column', gap: 0 },
  productFormRow: { display: 'flex', gap: 8, marginBottom: 8 },
  imageUploadRow: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, flexWrap: 'wrap' },
  uploadImgBtn: {
    padding: '6px 12px', borderRadius: r.sm,
    border: `1px dashed ${c.primary}`, background: c.primarySoft,
    color: c.primary, cursor: 'pointer', fontSize: 12, fontFamily: f,
  },
  productImgPreview: { width: 36, height: 36, objectFit: 'cover', borderRadius: 4 },
  primaryBtn: {
    padding: '9px 20px', borderRadius: r.md, border: 'none',
    background: c.primary, color: '#fff', cursor: 'pointer',
    fontSize: 13, fontWeight: 600, alignSelf: 'flex-start', fontFamily: f,
  },

  paymentGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, marginTop: 8 },
  paymentCard: {
    border: `1.5px solid ${c.border}`, borderRadius: r.lg,
    padding: '16px', cursor: 'pointer', background: c.surface,
    position: 'relative', transition: 'border-color 0.2s, background 0.2s',
    display: 'flex', flexDirection: 'column', gap: 4, boxShadow: tokens.shadow.card,
  },
  paymentCardActive: { borderColor: c.primary, background: c.primarySoft },
  paymentCheck: {
    position: 'absolute', top: 10, right: 10,
    width: 20, height: 20, borderRadius: 4,
    border: `1.5px solid ${c.border}`, background: c.surface,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  checkmark: { fontSize: 12, color: c.primary, fontWeight: 700 },
  paymentName: { fontSize: 14, fontWeight: 600, margin: 0, color: c.navy },
  paymentDesc: { fontSize: 12, color: c.textFaint, margin: 0 },

  colorGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, marginBottom: 20 },
  colorCard: {
    border: `1px solid ${c.border}`, borderRadius: r.lg,
    padding: '14px', background: c.surface,
    display: 'flex', alignItems: 'center', gap: 12, boxShadow: tokens.shadow.card,
  },
  colorPreviewWrap: { position: 'relative', flexShrink: 0 },
  colorSwatch: { width: 48, height: 48, borderRadius: r.md, border: '1px solid rgba(0,0,0,0.08)', cursor: 'pointer' },
  colorInput: { position: 'absolute', inset: 0, opacity: 0, cursor: 'pointer', width: '100%', height: '100%' },
  colorLabel: { fontSize: 13, fontWeight: 600, margin: 0, color: c.navy },
  colorDesc: { fontSize: 11, color: c.textFaint, margin: '2px 0 0' },
  colorHex: { fontSize: 11, fontFamily: 'monospace', color: c.primary, margin: '2px 0 0' },
  previewLabel: { fontSize: 11, fontWeight: 600, color: c.textMuted, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 8 },
  previewStrip: { borderRadius: r.lg, overflow: 'hidden', border: `1px solid ${c.border}` },
  previewHeader: { padding: '10px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  previewHeaderText: { fontSize: 13, fontWeight: 600, color: '#fff' },
  previewNav: { fontSize: 11, color: 'rgba(255,255,255,0.7)' },
  previewBody: { padding: 16, display: 'flex', gap: 12 },
  previewProductCard: { flex: 1, background: 'rgba(255,255,255,0.9)', borderRadius: r.md, padding: 10, display: 'flex', flexDirection: 'column', gap: 6 },
  previewProductImg: { width: '100%', height: 60, background: c.border, borderRadius: r.sm },
  previewProductName: { fontSize: 11, fontWeight: 500, color: '#1e293b', margin: 0 },
  previewProductPrice: { fontSize: 11, color: c.textMuted, margin: 0 },
  previewBtn: { fontSize: 11, color: '#fff', padding: '4px 8px', borderRadius: 4, textAlign: 'center', fontWeight: 600 },
  previewFooter: { padding: '10px 16px', textAlign: 'center' },
  previewFooterText: { fontSize: 11, color: 'rgba(255,255,255,0.5)' },

  aiLayout: { display: 'flex', gap: 16, minHeight: 420 },
  aiContextPanel: {
    width: 200, flexShrink: 0, border: `1px solid ${c.border}`,
    borderRadius: r.lg, background: c.surface, padding: 14,
    boxShadow: tokens.shadow.card,
  },
  contextItem: { display: 'flex', flexDirection: 'column', gap: 2, marginBottom: 12 },
  contextLabel: { fontSize: 10, fontWeight: 600, color: c.textFaint, textTransform: 'uppercase', letterSpacing: '0.05em' },
  contextValue: { fontSize: 12, color: c.navy },
  colorPaletteMini: { display: 'flex', gap: 4, marginTop: 4 },
  colorDot: { width: 16, height: 16, borderRadius: 4, border: '1px solid rgba(0,0,0,0.1)' },
  chatPanel: {
    flex: 1, display: 'flex', flexDirection: 'column',
    border: `1px solid ${c.border}`, borderRadius: r.lg,
    background: c.surface, overflow: 'hidden', boxShadow: tokens.shadow.card,
  },
  chatMessages: { flex: 1, overflowY: 'auto', padding: 14, display: 'flex', flexDirection: 'column', gap: 10 },
  chatEmpty: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8 },
  chatBubble: { padding: '8px 12px', borderRadius: r.md, maxWidth: '85%' },
  chatBubbleUser: { alignSelf: 'flex-end', background: c.navy, color: '#fff' },
  chatBubbleAI: { alignSelf: 'flex-start', background: c.surfaceLow, border: `1px solid ${c.border}` },
  aiLabel: { fontSize: 9, fontWeight: 700, color: c.primary, textTransform: 'uppercase', letterSpacing: '0.08em', display: 'block', marginBottom: 3 },
  chatText: { fontSize: 13, margin: 0, lineHeight: 1.5, color: c.text },
  chatInputRow: { display: 'flex', gap: 8, padding: '10px 12px', borderTop: `1px solid ${c.border}` },
  sendBtn: {
    width: 36, height: 36, borderRadius: r.md, border: 'none',
    background: c.primary, color: '#fff', cursor: 'pointer', fontSize: 14, flexShrink: 0,
  },

  publishSummary: { display: 'flex', flexDirection: 'column', gap: 20 },
  summarySection: {},
  summaryTitle: { fontSize: 16, fontWeight: 700, color: c.navy, margin: '0 0 12px' },
  summaryGrid: { display: 'flex', gap: 12 },
  summaryCard: {
    flex: 1, background: c.surface, border: `1px solid ${c.border}`,
    borderRadius: r.lg, padding: '16px', display: 'flex', flexDirection: 'column',
    alignItems: 'center', gap: 4, boxShadow: tokens.shadow.card,
  },
  summaryNum: { fontSize: 28, fontWeight: 800, color: c.navy, lineHeight: 1 },
  summaryLabel: { fontSize: 11, color: c.textMuted, margin: 0 },
  urlPreview: { background: c.successSoft, border: `1px solid #a7f3d0`, borderRadius: r.lg, padding: '14px 18px' },
  urlText: { fontSize: 15, fontFamily: 'monospace', color: c.success, fontWeight: 600, margin: '6px 0 0' },
  colorPreviewRow: { display: 'flex', gap: 12 },
  colorPreviewItem: { display: 'flex', alignItems: 'center', gap: 6 },
  colorPreviewKey: { fontSize: 11, color: c.textMuted, textTransform: 'capitalize' },

  successScreen: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    minHeight: '100vh', gap: 16, background: c.background, textAlign: 'center', padding: 40, fontFamily: f,
  },
  successIcon: { fontSize: 48, color: c.success },
  successTitle: { fontSize: 28, fontWeight: 800, color: c.navy, margin: 0 },
  successUrl: { fontSize: 15, fontFamily: 'monospace', color: c.success, background: c.successSoft, padding: '8px 16px', borderRadius: r.md },
}
