import type { CSSProperties } from 'react'
import { tokens } from '@/lib/design/tokens'

/*
  Dashboard chrome styles — retuned to the "SaaS Commerce Modern" design system
  (Stitch). Values come from lib/design/tokens.ts so the whole merchant dashboard
  stays consistent with the rest of the app. Light sidebar + navy text + indigo
  active accent, matching the Stitch Merchant Dashboard reference.
*/
const c = tokens.color
const sp = tokens.space
const r = tokens.radius

export const S: Record<string, CSSProperties> = {
  root: {
    display: 'flex',
    minHeight: '100vh',
    background: c.background,
    fontFamily: tokens.font.sans,
    color: c.text,
  },

  sidebar: {
    width: 220,
    minWidth: 220,
    background: c.surface,
    borderInlineEnd: `1px solid ${c.border}`,
    display: 'flex',
    flexDirection: 'column',
    padding: '0 0 16px',
    position: 'relative',
    transition: 'width 0.25s, min-width 0.25s',
    flexShrink: 0,
  },
  sidebarCollapsed: {
    width: 60,
    minWidth: 60,
  },
  sidebarTop: {
    padding: '20px 14px 16px',
    borderBottom: `1px solid ${c.border}`,
    marginBottom: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    minHeight: 64,
  },
  brandRow: { display: 'flex', alignItems: 'center', gap: 10, minWidth: 0, flex: 1 },
  brandAvatar: {
    width: 32,
    height: 32,
    borderRadius: r.md,
    background: c.primary,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
    flexShrink: 0,
  },
  brandName: {
    fontSize: 13,
    fontWeight: 600,
    color: c.navy,
    margin: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  brandUrl: {
    fontSize: 10,
    color: c.textMuted,
    margin: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  planBadge: {
    fontSize: 10,
    fontWeight: 600,
    padding: '2px 7px',
    background: c.primarySoft,
    color: c.primary,
    borderRadius: r.sm,
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  nav: { display: 'flex', flexDirection: 'column', gap: 2, padding: '0 8px', flex: 1 },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '9px 10px',
    borderRadius: r.md,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: c.textMuted,
    fontSize: 13,
    transition: 'background 0.15s, color 0.15s',
    textAlign: 'start',
    width: '100%',
    position: 'relative',
  },
  navItemActive: {
    background: c.primarySoft,
    color: c.primary,
    fontWeight: 600,
  },
  navIcon: { fontSize: 15, flexShrink: 0, width: 18, textAlign: 'center' },
  navLabel: { fontSize: 13, flex: 1 },
  navDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    background: c.primary,
    flexShrink: 0,
  },
  sidebarFooter: {
    padding: '12px 16px 0',
    borderTop: `1px solid ${c.border}`,
    marginTop: 8,
  },
  storeLink: {
    fontSize: 12,
    color: c.textMuted,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  collapseBtn: {
    position: 'absolute',
    bottom: 20,
    insetInlineEnd: -12,
    width: 24,
    height: 24,
    borderRadius: '50%',
    background: c.surface,
    border: `1px solid ${c.border}`,
    color: c.textMuted,
    cursor: 'pointer',
    fontSize: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: tokens.shadow.card,
  },

  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 },
  topbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '18px 28px',
    background: c.surface,
    borderBottom: `1px solid ${c.border}`,
    flexShrink: 0,
  },
  pageTitle: { fontSize: 20, fontWeight: 600, margin: 0, letterSpacing: '-0.01em', color: c.navy },
  pageDate: { fontSize: 12, color: c.textFaint, margin: '3px 0 0' },
  topbarRight: { display: 'flex', alignItems: 'center', gap: 14 },
  periodToggle: {
    display: 'flex',
    border: `1px solid ${c.border}`,
    borderRadius: r.md,
    overflow: 'hidden',
  },
  periodBtn: {
    padding: '6px 12px',
    fontSize: 12,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: c.textMuted,
  },
  periodBtnActive: { background: c.primary, color: '#fff' },
  topbarAvatar: {
    width: 32,
    height: 32,
    borderRadius: r.md,
    background: c.primary,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
    fontWeight: 700,
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px 28px',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },

  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 14,
  },
  metricCard: {
    background: c.surface,
    border: `1px solid ${c.border}`,
    borderRadius: r.lg,
    padding: '16px 18px',
    cursor: 'pointer',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    boxShadow: tokens.shadow.card,
  },
  metricCardActive: { borderColor: c.primary, background: c.primarySoft },
  metricLabel: {
    fontSize: 11,
    color: c.textMuted,
    margin: '0 0 6px',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  metricValue: {
    fontSize: 24,
    fontWeight: 700,
    margin: '0 0 4px',
    letterSpacing: '-0.02em',
    color: c.navy,
  },
  metricUnit: { fontSize: 13, fontWeight: 400, color: c.textMuted },
  metricChange: { fontSize: 11, margin: 0 },

  middleRow: { display: 'grid', gridTemplateColumns: 'minmax(0, 1.7fr) minmax(0, 1fr)', gap: 16 },

  chartCard: {
    background: c.surface,
    border: `1px solid ${c.border}`,
    borderRadius: r.lg,
    padding: '18px 20px',
    boxShadow: tokens.shadow.card,
  },
  chartHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  cardTitle: { fontSize: 14, fontWeight: 600, margin: 0, color: c.navy },
  cardSub: { fontSize: 11, color: c.textFaint, margin: '3px 0 0' },
  chartTotal: { fontSize: 16, fontWeight: 700, color: c.primary, margin: 0 },
  chartDays: { display: 'flex', justifyContent: 'space-between', padding: '6px 12px 0' },
  chartDay: { fontSize: 11, color: c.textFaint },

  alertsCard: {
    background: c.surface,
    border: `1px solid ${c.border}`,
    borderRadius: r.lg,
    padding: '18px 16px',
    boxShadow: tokens.shadow.card,
  },
  alertsHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  alertBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: '2px 7px',
    background: c.warningSoft,
    color: c.warning,
    borderRadius: r.sm,
  },
  alertsList: { display: 'flex', flexDirection: 'column', gap: 10 },
  alertItem: { borderRadius: r.md, padding: '10px 12px', display: 'flex', flexDirection: 'column', gap: 6 },
  alertTitle: { fontSize: 12, fontWeight: 600, margin: 0, lineHeight: 1.3 },
  alertDesc: { fontSize: 11, color: c.textMuted, margin: 0, lineHeight: 1.4 },
  alertAction: {
    fontSize: 11,
    fontWeight: 600,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    alignSelf: 'flex-end',
  },

  bottomRow: { display: 'grid', gridTemplateColumns: 'minmax(0, 1.5fr) minmax(0, 1fr)', gap: 16 },
  sectionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  viewAllBtn: {
    fontSize: 12,
    color: c.primary,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 500,
  },

  ordersCard: {
    background: c.surface,
    border: `1px solid ${c.border}`,
    borderRadius: r.lg,
    padding: '18px 20px',
    boxShadow: tokens.shadow.card,
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    fontSize: 11,
    color: c.textMuted,
    fontWeight: 600,
    textAlign: 'start',
    padding: '0 8px 10px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    whiteSpace: 'nowrap',
  },
  tr: { borderTop: `1px solid ${c.border}` },
  td: { fontSize: 12, color: c.text, padding: '10px 8px', whiteSpace: 'nowrap' },
  orderId: { fontFamily: 'monospace', fontSize: 11, color: c.textMuted },
  statusBadge: { fontSize: 11, fontWeight: 500, padding: '3px 8px', borderRadius: r.sm, whiteSpace: 'nowrap' },

  productsCard: {
    background: c.surface,
    border: `1px solid ${c.border}`,
    borderRadius: r.lg,
    padding: '18px 18px',
    boxShadow: tokens.shadow.card,
  },
  productList: { display: 'flex', flexDirection: 'column', gap: 14 },
  productRow: { display: 'flex', alignItems: 'flex-start', gap: 10 },
  productRank: { fontSize: 11, color: c.textFaint, fontWeight: 700, width: 18, flexShrink: 0, marginTop: 2 },
  productMeta: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 5 },
  productName: { fontSize: 12, fontWeight: 500, color: c.text, margin: 0 },
  productCategory: {
    fontSize: 10,
    color: c.textMuted,
    background: c.surfaceLow,
    padding: '1px 6px',
    borderRadius: r.sm,
  },
  productBar: { height: 4, background: c.surfaceLow, borderRadius: 2, overflow: 'hidden', marginBottom: 5 },
  productBarFill: { height: '100%', background: c.primary, borderRadius: 2, transition: 'width 0.4s' },
  productStats: { display: 'flex', gap: 10 },
  productStat: { fontSize: 10, color: c.textMuted },

  comingSoon: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: '60px 0',
  },
  comingSoonText: { fontSize: 16, fontWeight: 500, color: c.textMuted, margin: 0 },
  comingSoonSub: { fontSize: 13, color: c.textFaint, margin: 0 },
}
