package com.example.flowmerceproject.PaymentManagement.dto;

import com.example.flowmerceproject.PaymentManagement.entity.Payment.PaymentStatus;
import com.example.flowmerceproject.PaymentManagement.entity.Wallet.OwnerType;
import com.example.flowmerceproject.PaymentManagement.entity.WalletTransaction.ReferenceType;
import com.example.flowmerceproject.PaymentManagement.entity.WalletTransaction.TransactionType;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PaymentDTOs {

    // ── REQUEST DTOs ──────────────────────────────────────────────────────────

    @Data @Builder @NoArgsConstructor @AllArgsConstructor
    public static class InitiatePaymentRequest {
        @NotNull(message = "Order ID is required")
        private Integer orderId;

        @NotNull(message = "Amount is required")
        @DecimalMin(value = "0.01", message = "Amount must be positive")
        private BigDecimal amount;

        @NotBlank(message = "Payment method is required")
        private String paymentMethod;

        /** Client-supplied UUID for idempotency. Auto-generated by server if absent. */
        private String idempotencyKey;
    }

    @Data
    public static class ConfirmPaymentRequest {
        /** Optional reference (e.g., bank receipt number, delivery confirmation). */
        private String reference;
        private String note;
    }

    @Data
    public static class RefundRequest {
        @NotNull(message = "Refund amount is required")
        @DecimalMin(value = "0.01", message = "Refund amount must be positive")
        private BigDecimal amount;
        private String reason;
    }

    @Data
    public static class TopUpRequest {
        @NotNull(message = "Amount is required")
        @DecimalMin(value = "1.00", message = "Minimum top-up is 1 EGP")
        private BigDecimal amount;
    }

    // ── RESPONSE DTOs ─────────────────────────────────────────────────────────

    @Data @Builder
    public static class PaymentResponse {
        private Integer paymentId;
        private Integer orderId;
        private String paymentMethod;
        private PaymentStatus status;
        private BigDecimal amount;
        private String currency;
        private String gateway;
        private String transactionReference;
        private String redirectUrl;
        private String failureReason;
        private LocalDateTime paidAt;
        private LocalDateTime createdAt;
    }

    @Data @Builder
    public static class WalletResponse {
        private Integer walletId;
        private OwnerType ownerType;
        private BigDecimal balance;
        private String currency;
        private Boolean isActive;
        private LocalDateTime createdAt;
    }

    @Data @Builder
    public static class WalletTransactionResponse {
        private Long transactionId;
        private BigDecimal amount;
        private TransactionType type;
        private ReferenceType referenceType;
        private Integer referenceId;
        private BigDecimal balanceAfter;
        private String description;
        private LocalDateTime createdAt;
    }

    /** Wrapper returned by POST /api/orders/place that bundles order + payment. */
    @Data @Builder
    public static class OrderPlaceResponse {
        private com.example.flowmerceproject.OrderManagement.dto.OrderDTOs.OrderResponse order;
        private PaymentResponse payment;
    }
}
